apiVersion: apps/vi
kind: Deployment
metadata:
  name: webapp
  labels:
    tier:  frontend
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: nginx